[package]
name = "demo_ccc_contract"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "0.16.1", default-features = false, features = [ "std" ] }
spin_sdk = { path = "../../spin_sdk" }
borsh = "0.10.3"
